from typing import TypeVar, Generic, Optional, Iterator

K = TypeVar("K")
V = TypeVar("V")

class LRUCache(Generic[K, V]):
    def __init__(self, capacity: int) -> None: ...
    def get(self, key: K) -> Optional[V]: ...
    def put(self, key: K, value: V) -> None: ...
    def delete(self, key: K) -> bool: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: K) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    @property
    def capacity(self) -> int: ...
    @property
    def size(self) -> int: ...
